// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicksterSampleApp.Infrastructure.Contexts;

#nullable disable

namespace TicksterSampleApp.Infrastructure.Migrations
{
    [DbContext(typeof(SampleAppContext))]
    [Migration("20250206102121_initcreate")]
    partial class initcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.Campaign", b =>
                {
                    b.Property<string>("TicksterCampaignId")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TicksterCommunicationId")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TicksterInternalReference")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("TicksterCampaignId", "TicksterCommunicationId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("char(2)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsCompany")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PostalAddressLineOne")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostalAddressLineTwo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TicksterUserRefNo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasTableReservation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductionName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicksterEventId")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TicksterProductionId")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.EventRestaurant", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId", "RestaurantId");

                    b.ToTable("EventRestaurants");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.Goods", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("CanBePlacedAtTable")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("PartOfSeasonToken")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartOfSeasonTokenGoodsId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("PartOfTableReservation")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceIncVatAfterDiscount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<Guid?>("PurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TicksterEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TicksterGoodsId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("VatPercent")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("VatPortion")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.ImportLog", b =>
                {
                    b.Property<int>("LastTicksterCrmId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LastTicksterCrmId", "Date");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.ToTable("ImportLogs");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscountCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DiscountCodeName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EogRequestCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivacyRefNo")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TermsRefNo")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<int>("TicksterCrmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TicksterPurchaseRefNo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("ToBePaidInRestaurantSystem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.PurchaseCampaign", b =>
                {
                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CampaignId")
                        .HasColumnType("TEXT");

                    b.HasKey("PurchaseId", "CampaignId");

                    b.ToTable("PurchaseCampaignLookup");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TicksterVenueId")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.Event", b =>
                {
                    b.HasOne("TicksterSampleApp.Domain.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.Goods", b =>
                {
                    b.HasOne("TicksterSampleApp.Domain.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("TicksterSampleApp.Domain.Models.Purchase", "Purchase")
                        .WithMany("Goods")
                        .HasForeignKey("PurchaseId");

                    b.Navigation("Event");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.Purchase", b =>
                {
                    b.HasOne("TicksterSampleApp.Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TicksterSampleApp.Domain.Models.Purchase", b =>
                {
                    b.Navigation("Goods");
                });
#pragma warning restore 612, 618
        }
    }
}
